services:
  redis:
    container_name: "Slavreddit_redis"
    image: redis
    restart: unless-stopped
    ports:
      - '6379:6379'

  mongodb:
    container_name: "Slavreddit_mongodb"
    image: 'mongo'
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    ports:
      - '27017:27017'
    volumes:
      - "../tmp/mongodb:/data/db"