services:
  redis:
    container_name: "Slavreddit_redis"
    image: 'redis-stack:latest'
    restart: unless-stopped
    ports:
      - '8001:8001'
      - '6379:6379'

  mongodb:
    container_name: "Slavreddit_mongodb"
    image: 'mongodb-community-server:latest'
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    ports:
      - '27017:27017'