HTTPServerConfig:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s

AuthConfig:
  access_token_ttl: 24h
  session_ttl: 43200s

RepoConfig:
  type: "db"

RedisConfig:
  network: "tcp"
  address: "localhost:6379"

MySQLConfig:
  username: "root"
  host: "localhost"
  port: "3306"
  db_name: "Slavreddit"
  max_open_conn: 10

MongoConfig:
  username: ""
  host: "localhost"
  port: "27017"
  db_name: "Slavreddit"
  collection_name: "posts"

MigrationConfig:
  attempts: 3
  timeout: 5
