HTTPServerConfig:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s

AuthConfig:
  access_token_ttl: 24h
  session_ttl: 43200s

RepoConfig:
  type: "db"

RedisConfig:
  network: "tcp"
  address: "localhost:6379"